name: Workflow Demo

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create a text file
      run: echo "Hello, world!" > hello.txt

    - name: Archive text file
      uses: actions/upload-artifact@v4.4.3
      with:
        name: hello-artifact
        path: hello.txt
    - name: download artifact
      uses: actions/download-artifact@v4.1.8
      with:
        name: hello-artifact
    - name: cat artifact
      run: cat hello.txt
    
